// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsXWRvYd8HLmTukr_6MSF_FEULmvgprwY',
    appId: '1:39709180221:web:125cb541168eb26cdc4554',
    messagingSenderId: '39709180221',
    projectId: 'omgisfirebasepaid',
    authDomain: 'omgisfirebasepaid.firebaseapp.com',
    storageBucket: 'omgisfirebasepaid.firebasestorage.app',
    measurementId: 'G-E91CCLXDWK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF453r4Ax-jZMju5f76CsD53OIimJZQ_A',
    appId: '1:39709180221:android:83f8594336e492a8dc4554',
    messagingSenderId: '39709180221',
    projectId: 'omgisfirebasepaid',
    storageBucket: 'omgisfirebasepaid.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyxohrU-6QIS8rz3QgbyCI91c4zLaTvWk',
    appId: '1:39709180221:ios:0d4270525ea3fb25dc4554',
    messagingSenderId: '39709180221',
    projectId: 'omgisfirebasepaid',
    storageBucket: 'omgisfirebasepaid.firebasestorage.app',
    androidClientId: '39709180221-f8ov1n38ifi2u24aee49ckv4n8pk44of.apps.googleusercontent.com',
    iosClientId: '39709180221-kuvtt2j1ffgcenojp3c01a64a1d569qi.apps.googleusercontent.com',
    iosBundleId: 'com.example.capjewel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyxohrU-6QIS8rz3QgbyCI91c4zLaTvWk',
    appId: '1:39709180221:ios:0d4270525ea3fb25dc4554',
    messagingSenderId: '39709180221',
    projectId: 'omgisfirebasepaid',
    storageBucket: 'omgisfirebasepaid.firebasestorage.app',
    androidClientId: '39709180221-f8ov1n38ifi2u24aee49ckv4n8pk44of.apps.googleusercontent.com',
    iosClientId: '39709180221-kuvtt2j1ffgcenojp3c01a64a1d569qi.apps.googleusercontent.com',
    iosBundleId: 'com.example.capjewel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsXWRvYd8HLmTukr_6MSF_FEULmvgprwY',
    appId: '1:39709180221:web:2585660d1d8027c3dc4554',
    messagingSenderId: '39709180221',
    projectId: 'omgisfirebasepaid',
    authDomain: 'omgisfirebasepaid.firebaseapp.com',
    storageBucket: 'omgisfirebasepaid.firebasestorage.app',
    measurementId: 'G-MBLS1P9C4M',
  );

}